### ISSUE TITLE
does not dispaly data on RN 0.68

### ISSUE THREAD

**Issue by Productivix** [deeksha-bit/react-native-barcode-zxing-scan#1]
hi, 
I do not understand , on React Native 0.68 , android sdk version 30, installation is OK but not "data" displayed .
How could we get also the barcode type please ?
thanks

**Comment by Productivix** [comment]
ok - works - but redeveloped internaly

**Comment by sangeeth3195** [comment]
Hi, 
I'm getting an undefined value while scanning the QR code in React Native 
can you please help me to fix that issue?
