### ISSUE TITLE
Getting Undefined value while scanning 

### ISSUE THREAD

**Issue by Sangeeth3195** [deeksha-bit/react-native-barcode-zxing-scan#2]
Hi,
I'm getting an undefined value while scanning the QR code in React Native
can you please help me to fix that issue?

**Comment by Productivix** [comment]
hi, 
to help == code , best photo of the QRcode

**Comment by Sangeeth3195** [comment]
Hi Productivix,

can you please share the sample code for reference?

 const handleClick = () => {
    try{
      BarcodeZxingScan.showQrReader(barcodeScanned);
      **console.log('barcodeScanned...' + BarcodeZxingScan.showQrReader(barcodeScanned));**
    }catch(error){
      console.log('error..code.. '  + error);
    }
  };

 const barcodeScanned = (data) => {
    console.log("Barcode......" + data);
  };

In console i'm getting undefined value ?
